create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid not null, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid not null, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid not null, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid not null, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid not null, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
create table table_books (id  bigserial not null, last_name varchar(255), book_name varchar(255), publish_date varchar(255), uuid uuid, primary key (id))
